services:
    # IDaS Envrioment
    idas_app:
        build:
            context: .
            dockerfile: Dockerfile
        image: processton/idas_php
        container_name: idas_app
        restart: unless-stopped
        tty: true
        ports:
            - '9001:9001'
        environment:
            SERVICE_NAME: idas_app
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ../:/var/www
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - idas
    idas_package:
        build:
            context: .
            dockerfile: Dockerfile
        image: processton/idas_php
        container_name: idas_package
        restart: unless-stopped
        tty: true
        ports:
            - '9002:9001'
        environment:
            SERVICE_NAME: idas_package
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ../packages/processton/processton-client/:/var/www
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - idas
    idas_webserver:
        image: nginx:alpine
        container_name: idas_webserver
        restart: unless-stopped
        tty: true
        ports:
            - "8001:80"
        volumes:
            - ../:/var/www
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - idas
        depends_on:
            - idas_app
    idas_node:
        build:
            context: .
            dockerfile: Dockerfile.node
        image: thedataflow/idas_node
        container_name: idas_node
        tty: true
        volumes:
            - ../:/app
        networks:
            - idas
    package_node:
        build:
            context: .
            dockerfile: Dockerfile.node
        image: thedataflow/idas_node
        container_name: package_node
        tty: true
        volumes:
            - ../packages/processton/processton-client:/app
        networks:
            - idas
    idas_storybook:
      build:
        context: .
        dockerfile: Dockerfile.storybook
      image: thedataflow/idas_storybook
      container_name: idas_storybook
      tty: true
      ports:
        - "9009:3001"
        - "6006:6006"
      volumes:
        - ../packages/processton/processton-client:/app
      networks:
        - idas
networks:
    idas:
        name: processton
        external: true